name: Heroku Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Heroku
        run: echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.heroku.com/redwoods/web .
          docker push registry.heroku.com/redwoods/web

      - name: Release to Heroku
        run: heroku container:release -a redwoods web

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}